---
  - name: PLAY 1 - CREATE A DATABASE OF ALL MACS
    hosts: Switches
    #    connection: local
    gather_facts: no

    tasks:

      - name: TASK1.1 - COLLECT MAC TABLE
        ios_command:
          commands:
            - show mac address-table
        register: output

      - name: TASK1.1 - DISPLAY MAC TABLE
        debug: var=output.stdout[0]

      - name: TASK2 - PYTHON TO CREATE MAC DATABASE
        mac_database:
          hostname: "{{ inventory_hostname }}"
          raw_data: "{{ output.stdout[0] }}"
          dest: ./python_mac_db.txt
        register: result2
